### ISSUE TITLE
fails to generate with multiple input YAML files from 0.17.3

### ISSUE THREAD

**Issue by Guslington** [cfndsl/cfndsl#422] opened 2019-10-03 11:28 UTC
We have started seeing this error since the 0.17.3 release with the changes made in #420 

```
cfndsl.rb:63:in `eval_file_with_extras': undefined method `merge' for "test":String (NoMethodError)
```

This only seems to occur when multiple yaml files are included when generating the template.

`test.rb`

```ruby
CloudFormation do
  topics.each do |topic|
    SNS_Topic("#{topic['name'].capitalize}Topic") {
      TopicName topic['name']
    }
  end
end
```

test.yaml

```yaml
topics:
  - name: test
  - name: another
```

test2.yaml

```yaml
property: test
```

generating template

```bash
cfndsl test.rb -y test.yaml -y test2.yaml -f yaml
```
error

```text
The creation of constants as config is deprecated!
Please switch to the #external_parameters method within your templates to access variables
See https://github.com/cfndsl/cfndsl/issues/170
Use the --disable-binding flag to suppress this message
Traceback (most recent call last):
	10: from /Users/gus/.rbenv/versions/2.5.3/bin/cfndsl:23:in `<main>'
	 9: from /Users/gus/.rbenv/versions/2.5.3/bin/cfndsl:23:in `load'
	 8: from /Users/gus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfndsl-0.17.3/bin/cfndsl:145:in `<top (required)>'
	 7: from /Users/gus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfndsl-0.17.3/lib/cfndsl.rb:65:in `eval_file_with_extras'
	 6: from /Users/gus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfndsl-0.17.3/lib/cfndsl.rb:65:in `each'
	 5: from /Users/gus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfndsl-0.17.3/lib/cfndsl.rb:71:in `block in eval_file_with_extras'
	 4: from /Users/gus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfndsl-0.17.3/lib/cfndsl/external_parameters.rb:50:in `add_to_binding'
	 3: from /Users/gus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfndsl-0.17.3/lib/cfndsl/external_parameters.rb:50:in `each_pair'
	 2: from /Users/gus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfndsl-0.17.3/lib/cfndsl/external_parameters.rb:56:in `block in add_to_binding'
	 1: from /Users/gus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfndsl-0.17.3/lib/cfndsl/external_parameters.rb:56:in `eval'
/Users/gus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfndsl-0.17.3/lib/cfndsl.rb:63:in `eval_file_with_extras': undefined method `merge' for "test":String (NoMethodError)
```

I've managed to fix it by altering the `add_to_binding` method to check to see if the key is of class Hash as well as checking if it's defined. 

```ruby
if bind.eval("defined? #{key}") && bind.eval("#{key}.class == Hash")
  bind.eval "#{key}.merge(#{val.inspect})"
else
  bind.eval "#{key} = #{val.inspect}"
end
```
However i cannot get the spec tests to fail in the same manner as my about example so i can't really validate this solution.

I am using both the rake task and the command line to test this with the same outcome.

**Comment by gergnz** [comment] 2019-10-03 21:43
Thanks @Guslington for raising this. @cmaxwellau thoughts?

**Comment by gergnz** [comment] 2019-10-06 03:46
I see what the issue is here @Guslington. It looks like you are using a deprecated feature.
```
The creation of constants as config is deprecated!
Please switch to the #external_parameters method within your templates to access variables
See https://github.com/cfndsl/cfndsl/issues/170
Use the --disable-binding flag to suppress this message
```

But I've actually reviewed the original PR, and believe I have an improved fix for this scenario. What I would suggest though is that you use the `--disable-binding` and include something to load your variables. e.g. to update your example:

```
# frozen_string_literal: true

require 'cfndsl'

CloudFormation do
  params = {}
  external_parameters.each_pair do |key, val|
    key = key.to_sym
    params[key] = val
  end

  params[:topics].each do |topic|
    SNS_Topic("#{topic['name'].capitalize}Topic") do
      TopicName topic['name']
    end
  end
end
```

**Closed** 2019-10-06 03:53 UTC
